export interface Category {
  slug: string;
  name: string;
  icon: string;
  description: string;
  color: string;
  complaints: string[];
  department: string;
}

export const CATEGORIES: Category[] = [
  {
    slug: "anna-canteen",
    name: "Anna Canteen",
    icon: "🍚",
    description: "Report food quality, hygiene and canteen service issues.",
    color: "from-orange-500 to-amber-500",
    department: "Civil Supplies Department",
    complaints: ["Food Quality", "Drinking Water", "Hygiene", "Staff Behaviour", "Food Quantity", "Others"],
  },
  {
    slug: "municipality",
    name: "Municipality",
    icon: "🏢",
    description: "Civic issues under municipal jurisdiction.",
    color: "from-blue-500 to-indigo-500",
    department: "Municipal Administration",
    complaints: [
      "Road Damage",
      "Drainage",
      "Garbage Collection",
      "Street Lights",
      "Water Leakage",
      "Illegal Construction",
      "Broken Footpath",
      "Mosquito Problems",
      "Tree Fallen",
      "Public Toilet",
      "Others",
    ],
  },
  {
    slug: "school",
    name: "School",
    icon: "🏫",
    description: "Report issues in government schools.",
    color: "from-emerald-500 to-teal-500",
    department: "School Education Department",
    complaints: [
      "Mid-Day Meal",
      "Teacher Absence",
      "Toilet Problem",
      "Drinking Water",
      "Electricity",
      "Broken Furniture",
      "Classroom Damage",
      "Bullying",
      "Transport",
      "Others",
    ],
  },
  {
    slug: "college",
    name: "College",
    icon: "🎓",
    description: "Report issues in colleges and higher education.",
    color: "from-purple-500 to-fuchsia-500",
    department: "Higher Education Department",
    complaints: [
      "Faculty",
      "Attendance",
      "Examinations",
      "Laboratory",
      "Library",
      "Hostel",
      "Transport",
      "Wi-Fi",
      "Ragging",
      "Infrastructure",
      "Others",
    ],
  },
  {
    slug: "hospital",
    name: "Hospital",
    icon: "🏥",
    description: "Public health & hospital service complaints.",
    color: "from-rose-500 to-red-500",
    department: "Health & Medical Department",
    complaints: ["Doctor Availability", "Medicine Shortage", "Cleanliness", "Ambulance Delay", "Staff Behaviour", "Others"],
  },
  {
    slug: "water-supply",
    name: "Water Supply",
    icon: "🚰",
    description: "Drinking water & pipeline issues.",
    color: "from-sky-500 to-cyan-500",
    department: "Public Health Engineering",
    complaints: ["No Water Supply", "Contaminated Water", "Low Pressure", "Pipeline Leakage", "Others"],
  },
  {
    slug: "electricity",
    name: "Electricity",
    icon: "⚡",
    description: "Power supply and electrical hazards.",
    color: "from-yellow-500 to-amber-500",
    department: "Electricity Department",
    complaints: ["Power Cut", "Voltage Fluctuation", "Damaged Transformer", "Fallen Wire", "Others"],
  },
  {
    slug: "garbage",
    name: "Garbage",
    icon: "🚮",
    description: "Solid waste and sanitation problems.",
    color: "from-lime-500 to-green-500",
    department: "Sanitation Department",
    complaints: ["Garbage Not Collected", "Overflowing Bins", "Illegal Dumping", "Dead Animal Disposal", "Others"],
  },
  {
    slug: "roads",
    name: "Roads",
    icon: "🛣️",
    description: "Potholes, damaged roads and footpaths.",
    color: "from-slate-500 to-gray-600",
    department: "Roads & Buildings",
    complaints: ["Potholes", "Damaged Road", "Missing Divider", "Broken Footpath", "Others"],
  },
  {
    slug: "traffic",
    name: "Traffic",
    icon: "🚦",
    description: "Signals, congestion and traffic hazards.",
    color: "from-red-500 to-orange-500",
    department: "Traffic Police",
    complaints: ["Signal Not Working", "Traffic Congestion", "Illegal Parking", "Missing Signboard", "Others"],
  },
  {
    slug: "environment",
    name: "Environment",
    icon: "🌳",
    description: "Pollution, tree felling and ecology issues.",
    color: "from-green-500 to-emerald-600",
    department: "Environment Department",
    complaints: ["Air Pollution", "Noise Pollution", "Tree Cutting", "Water Pollution", "Others"],
  },
  {
    slug: "police",
    name: "Police",
    icon: "🚔",
    description: "Non-emergency police & safety complaints.",
    color: "from-blue-700 to-indigo-700",
    department: "Home Department",
    complaints: ["Public Nuisance", "Missing Person", "Cyber Crime", "Harassment", "Others"],
  },
  {
    slug: "government-offices",
    name: "Government Offices",
    icon: "💼",
    description: "Service delays and misconduct in offices.",
    color: "from-indigo-500 to-blue-600",
    department: "General Administration",
    complaints: ["Service Delay", "Staff Absence", "Document Issue", "Others"],
  },
  {
    slug: "corruption",
    name: "Corruption",
    icon: "💸",
    description: "Report bribery, extortion, embezzlement, or misconduct by public officials.",
    color: "from-red-600 to-amber-600",
    department: "Anti-Corruption Bureau",
    complaints: ["Bribery", "Extortion", "Embezzlement", "Misconduct", "Others"],
  },
];

export function getCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}